from django.urls import path

from .views import (
    api_root_view,
    checkout_view,
    dashboard_insights_view,
    dashboard_stats_view,
    login_view,
    low_stock_products_view,
    logout_view,
    me_view,
    product_detail_view,
    products_view,
    register_view,
    reset_password_view,
    sale_receipt_pdf_view,
    sale_receipt_email_view,
    sale_receipt_view,
    sales_report_detail_view,
    sales_report_view,
    sales_view,
    section_detail_view,
    sections_view,
    user_performance_view,
)

urlpatterns = [
    path("", api_root_view),
    path("auth/register", register_view),
    path("auth/login", login_view),
    path("auth/logout", logout_view),
    path("auth/me", me_view),
    path("auth/reset-password", reset_password_view),
    path("sections", sections_view),
    path("sections/<int:section_id>", section_detail_view),
    path("products", products_view),
    path("products/low-stock", low_stock_products_view),
    path("products/<int:product_id>", product_detail_view),
    path("checkout", checkout_view),
    path("sales", sales_view),
    path("sales/<int:sale_id>", sale_receipt_view),
    path("sales/<int:sale_id>/receipt.pdf", sale_receipt_pdf_view),
    path("sales/<int:sale_id>/receipt/email", sale_receipt_email_view),
    path("dashboard/stats", dashboard_stats_view),
    path("dashboard/insights", dashboard_insights_view),
    path("reports", sales_report_view),
    path("reports/details", sales_report_detail_view),
    path("users/performance", user_performance_view),
]
